developer/urls.py
from developer.views import DeveloperView, AboutView, SampleView, ContactView, EmailView
from django.urls import path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', DeveloperView.as_view(), name='developer'),
    path('about', AboutView.as_view(), name='about'),
    path('sample', SampleView.as_view(), name='sample'),
    path('contact', ContactView.as_view(), name='contact'),
    path('sendmail', EmailView.as_view(), name='sendmail'),
]

menu/urls.py
from django.urls import path
from menu.views import MenuView

urlpatterns = [
    path('', MenuView.as_view(), name='menu'),
]

developer/models.py
from django.db import models


class Message(models.Model):
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    #project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    created_on = models.DateField(auto_now_add=True)
    message = models.TextField(null=True)
    
    def __str__(self):
        return self.name + ", " + self.phone + ", " + self.email + ", " + self.message

developer/forms.py
from django import forms
from .models import Message

class ContactForm(forms.ModelForm):
    
    class Meta:
        model = Message
        exclude = ('',)

developer/views.py
#from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from developer.forms import ContactForm
from django.shortcuts import reverse
import boto3
import logging

log = logging.getLogger("workTracker")

class DeveloperView(TemplateView):
    template_name = 'developer/index.html'
    
class AboutView(TemplateView):
    template_name = 'developer/about.html'
    
class SampleView(TemplateView):
    template_name = 'developer/post.html'
    
class ContactView(FormView):

    form_class = ContactForm
    success_url = 'sendmail'
    template_name = 'developer/contact.html'
    client = boto3.client('ses', region_name='us-east-1')

    def form_valid(self, form):
        log.debug('Form valid called')
        log.debug(form.cleaned_data['phone'])
        whatTheyWant = form.cleaned_data['message'] + '<br><p>Call them: ' + form.cleaned_data['phone'] + '</p><br><p>Email them: ' + form.cleaned_data['email']
        """If the form is valid, save the associated model."""
        self.object = form.save()
        response = self.client.send_email(
            Source='ryan@seniordevops.com',
            Destination={
                'ToAddresses': [
                    'ryan.dines@gmail.com',
                ],
            },
            Message={
                'Subject': {
                    'Data': form.cleaned_data['name'],
                },
                'Body': {
                    'Text': {
                        'Data': 'IDFK this does',
                    },
                    'Html': {
                        'Data': whatTheyWant,
                    }
                }
            },
            ReplyToAddresses=[
                'ryan@seniordevops.com',
            ]
        )
        log.debug(response)
        # return super(ContactView, self).form_valid(form)
        return super().form_valid(form)
    
class EmailView(TemplateView):
    template_name = 'developer/sendEmail.html'    

developer/templates/developer/about.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Senior DevOps</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link href="{% static 'developer/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'developer/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'developer/css/clean-blog.min.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'menu' %}">Home</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url({% static 'img/about-bg.jpg' %})">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading"  style="padding:50px">
              <h1>Senior DevOps</h1>
              <span class="subheading">Software is what we do.  Cloud deployments, virtual private servers, advanced network analysis.  From a simple custom software solution to a large scale project, we have you covered.</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>At seniorDevops.com, we specialize in writing and deploying custom software for any size budget.  Web development, mobile apps, data-mining, security analysis, complex deployments, whatever your IT needs are, we have the right team for the job.  
          </p>
          <p>We’ve designed a system to track and deploy projects daily, so you’ll be in daily contact with the lead developer to guide the process.  This ensures that you get what you pay for as customer, and allows us as a team to focus on your needs and stay under budget.</p>
          <p>The code is tracked in the cloud and so you’ll also get statistics like the number of lines of code added and deleted daily.  Track the quality, track the quantity, if you’re a perfectionist with deadlines, we’re the no nonsense company for you.</p>
        </div>
      </div>
    </div>
    <hr>
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Senior DevOps 2018</p>
          </div>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'developer/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'developer/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'developer/js/clean-blog.min.js' %}"></script>

  </body>

</html>

developer/templates/developer/contact.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Senior DevOps</title>
    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link href="{% static 'developer/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="{% static 'developer/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
    <script src='https://www.google.com/recaptcha/api.js'></script>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'menu' %}">Home</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Page Header -->
    <header class="masthead" style="background-image: url({% static 'img/contact-bg.jpg' %})">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading"  style="padding:50px">
              <h1>Contact Us</h1>
              <span class="subheading">Have questions? We have answers.</span>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Want to get in touch? Fill out the form below to send us a message and we will get back to you as soon as possible.</p>
          <form name="sentMessage" id="contactForm" novalidate method="post" action="{% url 'contact' %}">
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Name</label>
                {{ form.name }}
                {% csrf_token %}
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Email Address</label>
                {{ form.email }}
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label>Phone Number</label>
                {{ form.phone }}
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Message or description of project</label>
                {{ form.message }}
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <br>
            <div id="success"></div>
	          <div class="g-recaptcha" data-sitekey="6Lc6rVIUAAAAAKIyufRXlshHeyzLaZlm6xZO15w9"></div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary" id="sendMessageButton" style="margin-top:24px">Send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <hr>
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Senior DevOps 2018</p>
          </div>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'developer/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'developer/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <!--script src="{% static 'js/contact_me.js' %}"></script-->
    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
  </body>
</html>
<script>
    function csrfSafeMethod(method) {
        // don't reveal CSRF token to GET requests
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader('X-CSRFToken', csrftoken);
            }
        }
    });
    $("#id_name").attr({
        type: "text",
        class:"form-control", 
        placeholder: "Name",
        required: "true",
    });
    $("#id_email").attr({
        type: "email",
        class:"form-control", 
        placeholder: "Email Address",
        required: "true",
    });
    $("#id_phone").attr({
        type: "email",
        class:"form-control", 
        placeholder: "Phone Number",
        required: "true",
    });
    $("#id_message").attr({
        type: "email",
        class:"form-control", 
        placeholder: "Message",
        required: "true",
    });
</script>

developer/templates/developer/index.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Developer's Corner</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link href="{% static 'developer/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'developer/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'developer/css/clean-blog.min.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'menu' %}">Sales</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'developer' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/home-bg.jpg" %}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading" style="padding:50px">
              <h1 style="transform:rotate(-7deg);">Developer's Corner</h1>
              <span class="subheading">Tutorials and articles on full stack software development</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-preview">
            <a href="{% url 'sample' %}">
              <h2 class="post-title">
                Visual Coding is Dead
              </h2>
              <h3 class="post-subtitle">
                Why use a modern technology stack
              </h3>
            </a>
            <p class="post-meta">Posted on April 5, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="{% url 'sample' %}">
              <h2 class="post-title">
                I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
              </h2>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on September 18, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="{% url 'sample' %}">
              <h2 class="post-title">
                Science has not yet mastered prophecy
              </h2>
              <h3 class="post-subtitle">
                We predict too much for the next year and yet far too little for the next ten.
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on August 24, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="{% url 'sample' %}">
              <h2 class="post-title">
                Failure is not an option
              </h2>
              <h3 class="post-subtitle">
                Many say exploration is part of our destiny, but it’s actually our duty to future generations.
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on July 8, 2018</p>
          </div>
          <hr>
          <!-- Pager -->
          <div class="clearfix">
            <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
          </div>
        </div>
      </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Senior DevOps 2018</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'developer/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'developer/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'developer/js/clean-blog.min.js' %}"></script>

  </body>

</html>

developer/templates/developer/post.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Senior DevOps</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'menu' %}">Sales</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'developer' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url({% static 'img/post-bg.jpg' %})">
      <div class="overlay"></div>
      <div class="container">
        <div class="row" >
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading" style="padding:50px;">
              <h1>Visual coding is dead</h1>
              <h2 class="subheading" style="margin-left:60px">Why use a modern technology stack</h2>
              <span class="meta">Posted on April 5, 2018</span>
                <!--a href="#">Start Bootstrap</a>
                on August 24, 2018</span-->
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p>Not that long ago, a trend started to give everyone a slice of the internet.  Point, click, visualize the content, no code required was the idea.  Wordpress began as a place to build a blog, but later grew into a content management system that powers 1/5 of all websites today.  Microsoft embraced the idea of visual coding with its Silverlight plug-in, which doesn’t require knowing code to make the user interface, and in fact, its IDE is named VisualStudio after the same concept.  </p>

            <h2 class="section-heading">The Times are a changing</h2>

            <p>Fast forward a decade later and Microsoft has adopted many of the decoupling strategies of a Linux stack in its newest product, .NET Core.   So what happened to plug-ins like Silverlight?  The internet got leaner; more people started using devices instead of computers, and in addition to the bulkiness of plug-ins, there were constant security problems.</p>

            <p>Modern technology stacks attempt to strike that balance between ease of use, speed, and security.  By separating the client-side and server-side technologies, each one is maximized separately for latency and security; technologies like CDNs and REST services are an example.</p>

            <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

            <p>But where is the market headed for developers?  Here are 2 stacks that I recently used professionally:</p>
            <p>Linux:</p>
            <p>Centos7/RHEL, gunicorn, nginx, python, Django, DjangoREST, Postgres, Bootstrap</p>
            <p>Windows:</p>
            <p>IIS, .NET Core, C#, MVC 6 with WebApi, ORM-based backend, KendoUI</p>
            <h2 class="section-heading">Picking the right stack</h2>
            <p>If the old code is Windows based, .NET Core has some great tools for making fast, secure applications.  For brand new applications, Python on a Linux stack is the way to go.  Python is pretty robust for data-mining and website testing, so why not use it for APIs and web development.  Python's Django comes with middleware, authentication, an ORM, and pretty much any module you can think of to do anything can be added.</p>
            <a href="#">
              <img class="img-fluid" src="{% static 'img/post-sample-image.jpg' %}" alt="">
            </a>
            <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
            <p>I left out some big names…Java, Node, pHp, Ruby, Perl, Go, NoSQL, React, Vue, Angular.  If you do full stack development, what’s your preference?  Comment below.</p>
            <p>Want to modernize your stack?  Ditching old tech like Silverlight or WordPress?  Contact us here: Link</p>
          </div>
        </div>
      </div>
    </article>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

  </body>

</html>

developer/templates/developer/sendEmail.html
Email sent